# Generated by Django 2.1.5 on 2019-03-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.CharField(default='DEFAULT', max_length=128, unique=True),
        ),
    ]
