# Generated by Django 2.1.5 on 2019-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20190321_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(),
        ),
    ]
