# Generated by Django 2.1.5 on 2019-03-29 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20190321_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(through='meeting.Relate', to=settings.AUTH_USER_MODEL),
        ),
    ]
