# Generated by Django 2.1.5 on 2019-04-02 22:59

from django.db import migrations, models
import meeting.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_auto_20190329_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_source',
            field=models.FileField(upload_to=meeting.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
