# Generated by Django 2.1.5 on 2019-04-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_file_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='attached_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.File'),
        ),
    ]
