# Generated by Django 2.1.5 on 2019-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_auto_20190403_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
